{
 "title": "vulnerability dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "VULNERABILITY", "label": "VULNERABILITY", "query": "SELECT vuln_id from vuln" },
   { "name": "CPE", "label": "Enter CPE ", "query": "SELECT DISTINCT name FROM cpe;" },
   {
    "name": "CWE",
    "label": "CWE",
    "query": "SELECT DISTINCT cwe_id FROM cwe;"
   }
  ]
 },
 "panels": [
  {
   "title": "VULN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scoring",
     "type": "barchart",
     "description": "Shows base score, impact score and exploitability score.",
     "gridPos": { "h": 7, "w": 23, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT \r\n    vuln_id AS \"Vulnerability ID\", \r\n    (data->'metrics'->'cvssMetricV2'->0->'cvssData'->>'baseScore')::float AS \"BaseScore\",\r\n    (data->'metrics'->'cvssMetricV2'->0->>'impactScore')::float AS \"ImpactScore\",\r\n    (data->'metrics'->'cvssMetricV2'->0->>'exploitabilityScore')::float AS \"ExploitabilityScore\"\r\nFROM \r\n    vuln \r\nWHERE \r\n    vuln_id IN ($VULNERABILITY)\r\nLIMIT 50;"
      }
     ]
    },
    {
     "title": "VULN",
     "type": "table",
     "gridPos": { "h": 12, "w": 23, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT \r\n    vuln_id, \r\n    published_date, \r\n    last_modified_date, \r\n    description,\r\n    (data->'metrics'->'cvssMetricV2'->0->'cvssData'->>'baseScore')::float AS \"BaseScore\",\r\n    (data->'metrics'->'cvssMetricV2'->0->>'impactScore')::float AS \"ImpactScore\",\r\n    (data->'metrics'->'cvssMetricV2'->0->>'exploitabilityScore')::float AS \"ExploitabilityScore\"\r\nFROM \r\n    vuln \r\nWHERE \r\n    vuln_id IN ($VULNERABILITY)\r\nLIMIT 50;"
      }
     ]
    }
   ]
  },
  {
   "title": "CPE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPE",
     "type": "table",
     "gridPos": { "h": 5, "w": 23, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT id, name, name_id, sys_creation_date, vendor, product \r\nFROM cpe\r\nWHERE name IN ($CPE)\r\nLIMIT 50;"
      }
     ]
    }
   ]
  },
  { "title": "CWE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CWE",
   "type": "table",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    id, \r\n    cwe_id, \r\n    name, \r\n    status, \r\n    description\r\nFROM \r\n    cwe\r\nWHERE cwe_id IN ($CWE)\r\nLIMIT 50;"
    }
   ]
  }
 ]
}