#!/bin/bash

branch=$(git branch --show-current)
export INP_ENV_NAME=${1:-test}
export FCDB_HOME=$(pwd)/src
export DOCKER_TAG=$branch
export CI_BUILD_REF_NAME=$branch
export POSTGRES_PASSWORD=new_password
export FCDB_USER=your_fastcve_db_user
export FCDB_PASS=your_fastcve_db_password
. ./src/config/setenv.sh

export PYTHONPATH=${FCDB_HOME}/src
